name = "tail-worker"
main = "src/worker.js"
compatibility_date = "2023-07-17"

workers_dev = false

[vars]
ENV = "dev"
DEBUG = "true"

#
# Staging
#
[env.staging]
account_id = "4b04db071e62c1a6196639e9aa112d1b"

[env.staging.vars]
ENV = "staging"
DEBUG = "false"

#
# Live
#
[env.live]
account_id = "4b04db071e62c1a6196639e9aa112d1b"

[env.live.vars]
ENV = "live"
DEBUG = "false"
